fixathing
elmsln/lrnwebcomponents pull request #560
Opened 2021-09-03 17:55 UTC by hvk5388

fixes local storgage

2021-09-07 14:07 UTC, btopro requested changes
Make sure to clean up `window.localStorageGet` and add similar wrappers for the sessionStorage getters / setters. To test that it's all working, invoke `yarn start` in the `elements/hax-body` directory. If it spins up and you can play with HAX without issues (like checking console) then it's probably working. We usually fire up HAX when a lot of things touch it and do a "will it blend" test :)

2021-09-07 14:07 UTC, btopro commented on elements/hax-body/lib/hax-store.js
> +      if (window.localStorageGet("haxConfirm")) {
remove the `window.` from these `localStorageGet` and `localStorageSet` calls as the window is not accurate here.

2021-09-07 14:07 UTC, btopro commented on elements/hax-body/lib/hax-store.js
> +        window.localStorageSet("haxUserData", JSON.stringify(newValue));
here too

2021-09-07 14:07 UTC, btopro commented on elements/hax-body/lib/hax-store.js
> +    window.localStorageSet("haxConfirm", true);
here too

2021-09-07 14:07 UTC, btopro commented on elements/hax-body/lib/hax-store.js
> +    window.localStorageSet(
here too

2021-09-07 14:07 UTC, btopro commented on elements/hax-body/lib/hax-store.js
> +      window.localStorageSet("haxConfirm", true);
here too

2021-09-07 14:07 UTC, btopro commented on elements/hax-body/lib/hax-store.js
> +      window.localStorageGet("haxConfirm");
here too

2021-09-07 14:07 UTC, btopro commented on elements/hax-body/lib/hax-store.js
> +        !window.localStorageGet("haxConfirm")
here too

2021-09-07 14:07 UTC, btopro commented on elements/hax-body/lib/hax-store.js
>          window.sessionStorage.getItem("haxConfirm") &&
Let's create a similar solution for `sessionStorage` as it's an identical API and could also suffer the same issues -- https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

2021-09-08 16:22 UTC, hvk5388 commented
I should have fixed everything...

2021-09-08 16:25 UTC, btopro commented
looks that way. Going to accept and pull down locally to do some deeper testing. keep it up!

2021-09-08 16:25 UTC, merged